# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs: 
  build:
    docker: 
      - image: gridlabd/slac-master:latest
    steps: 
      - checkout 
      - run: 
          name: Create output folder
          command: |
            mkdir output
      - run:
          name: Run the simulation
          command: |
            python3 run_model.glm
      - store_artifacts: 
            path: /root/project/output
